my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', 'webapp')),
    path('auth/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/webapp/urls.py
from django.urls import path
from webapp.views.author import AuthorListView, AuthorDetailView, AuthorCreateView, AuthorUpdateView, delete_author
from webapp.views.book import BookListView, BookDetailView, BookCreateView, BookUpdateView, delete_book, download_file
from webapp.views.user import UserView, UserListView, add_to_bookcase, remove_from_bookcase
from webapp.views.comment import comment

app_name = 'webapp'

urlpatterns = [
    path('user/<int:pk>/', UserView.as_view(), name = 'user_detail'),
    path('users/', UserListView.as_view(), name='users'),

    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author'),
    path('author/create/', AuthorCreateView.as_view(), name='create_author'),
    path('author/<int:pk>/update/', AuthorUpdateView.as_view(), name='update_author'),
    path('author/<int:author_pk>/delete/', delete_author, name='delete_author'),

    path('', BookListView.as_view(), name='books'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book'),
    path('book/create/', BookCreateView.as_view(), name='create_book'),
    path('book/<int:pk>/update/', BookUpdateView.as_view(), name='update_book'),
    path('book/<int:book_pk>/delete/', delete_book, name='delete_book'),
    path('download/<int:book_pk>', download_file, name='download'),


    path('add/to/bookcase/<int:book_pk>', add_to_bookcase, name='add_to_bookcase'),
    path('remove/from/bookcase/<int:book_pk>', remove_from_bookcase, name='remove_from_bookcase'),

    path('book/comment/create/', comment, name='create_comment'),
]

my_project/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name='Автор')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    death_date = models.DateField(null=True, blank=True, verbose_name='Дата смерти')
    biography = models.TextField(null=True, blank=True, max_length=2000, verbose_name='Биография')
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeleteManager()

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse('webapp:author', kwargs={'pk': self.pk})


class Book(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор')
    published_year = models.CharField(max_length=4, null=True, blank=True, verbose_name='Год издания')
    file = models.FileField(null=True, blank=True, verbose_name='Файл')
    picture = models.ImageField(null=True, blank=True, verbose_name='Обложка')
    description = models.TextField(null=True, blank=True, max_length=2000, verbose_name='Описание')
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeleteManager()

    def __str__(self):
        return "%s (%s)" % (self.name, self.published_year)

    def get_absolute_url(self):
        return reverse('webapp:book', kwargs={'pk': self.pk})


class Bookcase(models.Model):
    user = models.ForeignKey(User, related_name='user_bookcase', on_delete=models.CASCADE, verbose_name='Полка пользователья')
    book = models.ForeignKey('Book', related_name='book_bookcase', on_delete=models.CASCADE, verbose_name='Книга на полке')

    def __str__(self):
        return "Полка %s. Книга: %s" % (self.user.username, self.book.name)


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE,
                             verbose_name='Отзыв пользователья')
    book = models.ForeignKey('Book', related_name='book_comment', on_delete=models.CASCADE,
                             verbose_name='Отзыв к книге')
    text = models.TextField(max_length=2000, verbose_name='Отзыв', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Полка %s. Книга: %s. Отзыв №%s" % (self.user.username, self.book.name, self.pk)

my_project/webapp/forms.py
from django import forms
from webapp.models import Author, Book, Comment


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        exclude = ['is_deleted']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none is-valid',
                       'placeholder': 'ФИО', 'required': True}),
            'birth_date': forms.DateInput(
                attrs={'class': 'form-control form-control-sm shadow-none'}),
            'death_date': forms.DateInput(
                attrs={'class': 'form-control form-control-sm shadow-none'}),
            'biography': forms.Textarea(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Биография'}),
        }


class BookForm(forms.ModelForm):
    author = forms.ChoiceField

    class Meta:
        model = Book
        exclude = ['is_deleted']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none is-valid',
                       'placeholder': 'Название', 'required': True}),
            'published_year': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Год издания'}),
            'file': forms.FileInput(),
            'picture': forms.FileInput(),
            'description': forms.Textarea(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Описание'}),
        }

my_project/webapp/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author
from webapp.forms import AuthorForm


class BaseView(LoginRequiredMixin, TemplateView):
    template_name = 'base.html'


class AuthorListView(ListView):
    model = Author
    template_name = 'Author/list.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'Author/detail.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    template_name = 'Author/create.html'
    form_class = AuthorForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    template_name = 'Author/update.html'
    form_class = AuthorForm

    def get_queryset(self):
        return Author.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_author(request, author_pk):
    if request.user.is_staff:
        author = get_object_or_404(Author, pk=author_pk)
        author.is_deleted = True
        author.save()
    return redirect('webapp:authors')

my_project/webapp/views/author.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author, Book
from webapp.forms import AuthorForm


class AuthorListView(ListView):
    model = Author
    template_name = 'author/author_list.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author/author_detail.html'

    def get_queryset(self):
        return Author.objects.active()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.filter(author=self.object.pk, is_deleted=False)
        return context


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    template_name = 'author/author_create.html'
    form_class = AuthorForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    template_name = 'author/author_update.html'
    form_class = AuthorForm

    def get_queryset(self):
        return Author.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_author(request, author_pk):
    if request.user.is_staff:
        author = get_object_or_404(Author, pk=author_pk)
        author.is_deleted = True
        author.save()
    return redirect('webapp:authors')

my_project/webapp/views/book.py
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author, Book, Comment
from webapp.forms import BookForm


class BookListView(ListView):
    model = Book
    template_name = 'book/book_list.html'

    def get_queryset(self):
        return Book.objects.active()


class BookDetailView(DetailView):
    model = Author
    template_name = 'book/book_detail.html'

    def get_queryset(self):
        return Book.objects.active()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(book_id=self.object.pk).order_by('-created_date')
        return context


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    template_name = 'book/book_create.html'
    form_class = BookForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    template_name = 'book/book_update.html'
    form_class = BookForm

    def get_queryset(self):
        return Book.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_book(request, book_pk):
    print(book_pk)
    book = get_object_or_404(Book, pk=book_pk)
    if request.user.is_staff:
        book.is_deleted = True
        book.save()
    return redirect('webapp:books')


def download_file(request, book_pk):
    book = get_object_or_404(Book, pk = book_pk)
    path = book.file.path
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/file")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

my_project/webapp/views/comment.py
from django.shortcuts import redirect
from webapp.models import Comment


def comment(request):
    book_id = request.POST.get('book_id', '/')
    text = request.POST.get('text', '/')
    user_id = request.user.pk
    if request.user:
        Comment.objects.create(book_id=book_id, user_id=user_id, text=text)
    return redirect('webapp:book', pk=book_id)

my_project/webapp/views/user.py
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from webapp.models import Bookcase
from django.views.generic import DetailView, ListView


class UserView(DetailView):
    model = User
    template_name = 'user/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = []
        bookcase = Bookcase.objects.filter(user_id=self.object.pk)
        for item in bookcase:
            if item.book.is_deleted == False:
                context['books'].append(item.book)
        return context


class UserListView(ListView):
    model = User
    template_name = 'user/user_list.html'


@csrf_exempt
def add_to_bookcase(request, book_pk):
    if not request.user:
        raise HttpResponseForbidden
    try:
        Bookcase.objects.get(book_id=book_pk, user_id=request.user.pk)
    except:
        Bookcase.objects.create(book_id=book_pk, user_id=request.user.pk)
        return JsonResponse({'status': 'Успешно добавлено!'})
    else:
        return JsonResponse({'status': 'Уже на полке!'})


@csrf_exempt
def remove_from_bookcase(request, book_pk):
    if not request.user:
        raise HttpResponseForbidden
    try:
        Bookcase.objects.get(book_id=book_pk, user_id=request.user.pk).delete()
    except:
        return JsonResponse({'status': 'Такой книги нет, что то пошло не так!'})
    else:
        return JsonResponse({'status': 'Успешно удалено!'})

my_project/webapp/templates/base.html
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Arimo:400,700" rel="stylesheet">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3 border-bottom pb-0">
    <div class="container">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'webapp:books' %}">
                <span class="h5 mb-0 pb-0 font-weight-light">Библиотека</span>
            </a>
        </nav>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'webapp:books' %}"
                       class="nav-link text-dark font-weight-light">Книги</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:authors' %}"
                       class="nav-link text-dark font-weight-light">Авторы</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:users' %}"
                       class="nav-link text-dark font-weight-light">Пользователи</a>
                </li>
                {% block menu %}
                {% endblock %}
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item navbar-text text-light"><a href id="session_number"></a></li>
                    <li class="nav-item navbar-text text-dark">Привет,
                        <span class="text-capitalize font-weight-light border-bottom">
                            <a href='{% url "webapp:user_detail" user.pk %}'>{{ user.username }}</a>
                        </span> !
                    </li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link text-dark font-weight-light">Выход</a>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link text-dark">Вход</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}
{% endblock scripts %}
</body>
</html>

my_project/webapp/templates/delete_modal.html
<div class="modal fade" id="delete_item" tabindex="0" role="dialog" aria-labelledby="ModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content text-center">
            <div class="modal-header">
                <h5 class="m-auto">Вы уверены, что хотите удалить?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <a id="confirm_delete" class="btn btn-primary modal_btn" href='#'>Да</a>
                <a class="btn btn-secondary modal_btn" href="{{ request.path }}">Нет</a>
            </div>
        </div>
    </div>
</div>