my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', 'webapp')),
    path('auth/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/webapp/urls.py
from django.urls import path
from webapp.views.author import AuthorListView, AuthorDetailView, AuthorCreateView, AuthorUpdateView, delete_author
from webapp.views.book import BookListView, BookDetailView, BookCreateView, BookUpdateView, delete_book, download_file
from webapp.views.user import UserView, UserListView, add_to_bookcase, remove_from_bookcase
from webapp.views.comment import comment

app_name = 'webapp'

urlpatterns = [
    path('user/<int:pk>/', UserView.as_view(), name = 'user_detail'),
    path('users/', UserListView.as_view(), name='users'),

    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', AuthorDetailView.as_view(), name='author'),
    path('author/create/', AuthorCreateView.as_view(), name='create_author'),
    path('author/<int:pk>/update/', AuthorUpdateView.as_view(), name='update_author'),
    path('author/<int:author_pk>/delete/', delete_author, name='delete_author'),

    path('', BookListView.as_view(), name='books'),
    path('book/<int:pk>', BookDetailView.as_view(), name='book'),
    path('book/create/', BookCreateView.as_view(), name='create_book'),
    path('book/<int:pk>/update/', BookUpdateView.as_view(), name='update_book'),
    path('book/<int:book_pk>/delete/', delete_book, name='delete_book'),
    path('download/<int:book_pk>', download_file, name='download'),


    path('add/to/bookcase/<int:book_pk>', add_to_bookcase, name='add_to_bookcase'),
    path('remove/from/bookcase/<int:book_pk>', remove_from_bookcase, name='remove_from_bookcase'),

    path('book/comment/create/', comment, name='create_comment'),
]

my_project/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Author(models.Model):
    name = models.CharField(max_length=255, verbose_name='Автор')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    death_date = models.DateField(null=True, blank=True, verbose_name='Дата смерти')
    biography = models.TextField(null=True, blank=True, max_length=2000, verbose_name='Биография')
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeleteManager()

    def __str__(self):
        return "%s" % self.name

    def get_absolute_url(self):
        return reverse('webapp:author', kwargs={'pk': self.pk})


class Book(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    author = models.ForeignKey('Author', on_delete=models.CASCADE, verbose_name='Автор')
    published_year = models.CharField(max_length=4, null=True, blank=True, verbose_name='Год издания')
    file = models.FileField(null=True, blank=True, verbose_name='Файл')
    picture = models.ImageField(null=True, blank=True, verbose_name='Обложка')
    description = models.TextField(null=True, blank=True, max_length=2000, verbose_name='Описание')
    is_deleted = models.BooleanField(default=False)
    objects = SoftDeleteManager()

    def __str__(self):
        return "%s (%s)" % (self.name, self.published_year)

    def get_absolute_url(self):
        return reverse('webapp:book', kwargs={'pk': self.pk})


class Bookcase(models.Model):
    user = models.ForeignKey(User, related_name='user_bookcase', on_delete=models.CASCADE, verbose_name='Полка пользователья')
    book = models.ForeignKey('Book', related_name='book_bookcase', on_delete=models.CASCADE, verbose_name='Книга на полке')

    def __str__(self):
        return "Полка %s. Книга: %s" % (self.user.username, self.book.name)


class Comment(models.Model):
    user = models.ForeignKey(User, related_name='user_comment', on_delete=models.CASCADE,
                             verbose_name='Отзыв пользователья')
    book = models.ForeignKey('Book', related_name='book_comment', on_delete=models.CASCADE,
                             verbose_name='Отзыв к книге')
    text = models.TextField(max_length=2000, verbose_name='Отзыв', null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Полка %s. Книга: %s. Отзыв №%s" % (self.user.username, self.book.name, self.pk)

my_project/webapp/forms.py
from django import forms
from webapp.models import Author, Book, Comment


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        exclude = ['is_deleted']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none is-valid',
                       'placeholder': 'ФИО', 'required': True}),
            'birth_date': forms.DateInput(
                attrs={'class': 'form-control form-control-sm shadow-none'}),
            'death_date': forms.DateInput(
                attrs={'class': 'form-control form-control-sm shadow-none'}),
            'biography': forms.Textarea(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Биография'}),
        }


class BookForm(forms.ModelForm):
    author = forms.ChoiceField

    class Meta:
        model = Book
        exclude = ['is_deleted']
        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none is-valid',
                       'placeholder': 'Название', 'required': True}),
            'published_year': forms.TextInput(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Год издания'}),
            'file': forms.FileInput(),
            'picture': forms.FileInput(),
            'description': forms.Textarea(
                attrs={'class': 'form-control form-control-sm shadow-none',
                       'placeholder': 'Описание'}),
        }

my_project/webapp/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author
from webapp.forms import AuthorForm


class BaseView(LoginRequiredMixin, TemplateView):
    template_name = 'base.html'


class AuthorListView(ListView):
    model = Author
    template_name = 'Author/list.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'Author/detail.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    template_name = 'Author/create.html'
    form_class = AuthorForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    template_name = 'Author/update.html'
    form_class = AuthorForm

    def get_queryset(self):
        return Author.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_author(request, author_pk):
    if request.user.is_staff:
        author = get_object_or_404(Author, pk=author_pk)
        author.is_deleted = True
        author.save()
    return redirect('webapp:authors')

my_project/webapp/views/author.py
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author, Book
from webapp.forms import AuthorForm


class AuthorListView(ListView):
    model = Author
    template_name = 'author/author_list.html'

    def get_queryset(self):
        return Author.objects.active()


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author/author_detail.html'

    def get_queryset(self):
        return Author.objects.active()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.filter(author=self.object.pk, is_deleted=False)
        return context


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    template_name = 'author/author_create.html'
    form_class = AuthorForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    template_name = 'author/author_update.html'
    form_class = AuthorForm

    def get_queryset(self):
        return Author.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_author(request, author_pk):
    if request.user.is_staff:
        author = get_object_or_404(Author, pk=author_pk)
        author.is_deleted = True
        author.save()
    return redirect('webapp:authors')

my_project/webapp/views/book.py
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from webapp.models import Author, Book, Comment
from webapp.forms import BookForm


class BookListView(ListView):
    model = Book
    template_name = 'book/book_list.html'

    def get_queryset(self):
        return Book.objects.active()


class BookDetailView(DetailView):
    model = Author
    template_name = 'book/book_detail.html'

    def get_queryset(self):
        return Book.objects.active()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(book_id=self.object.pk).order_by('-created_date')
        return context


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    template_name = 'book/book_create.html'
    form_class = BookForm

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    template_name = 'book/book_update.html'
    form_class = BookForm

    def get_queryset(self):
        return Book.objects.active()

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


def delete_book(request, book_pk):
    print(book_pk)
    book = get_object_or_404(Book, pk=book_pk)
    if request.user.is_staff:
        book.is_deleted = True
        book.save()
    return redirect('webapp:books')


def download_file(request, book_pk):
    book = get_object_or_404(Book, pk = book_pk)
    path = book.file.path
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/file")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

my_project/webapp/views/comment.py
from django.shortcuts import redirect
from webapp.models import Comment


def comment(request):
    book_id = request.POST.get('book_id', '/')
    text = request.POST.get('text', '/')
    user_id = request.user.pk
    if request.user:
        Comment.objects.create(book_id=book_id, user_id=user_id, text=text)
    return redirect('webapp:book', pk=book_id)

my_project/webapp/views/user.py
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from webapp.models import Bookcase
from django.views.generic import DetailView, ListView


class UserView(DetailView):
    model = User
    template_name = 'user/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = []
        bookcase = Bookcase.objects.filter(user_id=self.object.pk)
        for item in bookcase:
            if item.book.is_deleted == False:
                context['books'].append(item.book)
        return context


class UserListView(ListView):
    model = User
    template_name = 'user/user_list.html'


@csrf_exempt
def add_to_bookcase(request, book_pk):
    if not request.user:
        raise HttpResponseForbidden
    try:
        Bookcase.objects.get(book_id=book_pk, user_id=request.user.pk)
    except:
        Bookcase.objects.create(book_id=book_pk, user_id=request.user.pk)
        return JsonResponse({'status': 'Успешно добавлено!'})
    else:
        return JsonResponse({'status': 'Уже на полке!'})


@csrf_exempt
def remove_from_bookcase(request, book_pk):
    if not request.user:
        raise HttpResponseForbidden
    try:
        Bookcase.objects.get(book_id=book_pk, user_id=request.user.pk).delete()
    except:
        return JsonResponse({'status': 'Такой книги нет, что то пошло не так!'})
    else:
        return JsonResponse({'status': 'Успешно удалено!'})

my_project/webapp/templates/book/book_create.html
{% extends 'base.html' %}
{% block title %}Добавление автора{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добавление автора</h2>
        <form action="{% url 'webapp:create_book' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'book/book_form.html' %}
            <button type="submit" class="btn btn-success m-2">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{% url 'webapp:authors' %}">Назад</a>
        </form>
    </div>
{% endblock %}

my_project/webapp/templates/book/book_detail.html
{% extends 'base.html' %}
{% block title %}Книга{% endblock %}
{% block content %}
    <div class="container">
        <div class="border-bottom pb-2 pb-3 mb-2">
            <h2 class="text-nowrap d-block mb-0 font-weight-bold">{{ book.name }}</h2>
            {% if book.picture %}
                <img src="{{ book.picture.url }}" alt="Обложка">
            {% endif %}
            <p class="d-block pb-0 mb-0 mt-1 ml-3 font-weight-bold">Автор:
                <span class="font-weight-light">
                    {% if book.author %} {{ book.author.name }} {% else %} Не указан {% endif %}
                </span>
            </p>
            <p class="d-block pb-0 mb-0 mt-1 ml-3 font-weight-bold">Год издания:
                <span class="font-weight-light">
                    {% if book.published_year %} {{ book.published_year }} {% else %} Не указан {% endif %}
                </span>
            </p>
            <p class="d-block pb-0 mb-0 mt-1 ml-3 font-weight-bold">Описание:
                <span class="font-weight-light">
                    {% if book.description %} {{ book.description }} {% else %} Нет {% endif %}
                </span>
            </p>
            <p class="d-block pb-0 mb-0 mt-1 ml-3 font-weight-bold">Файл:
                <span class="font-weight-light">
                    {% if book.file %}
                        {{ book.file }}
                        <a class="text-decoration-none text-dark d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1"
                           href="{% url 'webapp:download' book.pk %}"><span
                                class="small border-bottom border-warning pb-1">Скачать</span></a>
                    {% else %} Нет {% endif %}
                </span>
            </p>
        {% if user.is_authenticated %}
        <div class="input-group mt-5 mb-5">
            <form action="{% url 'webapp:create_comment' %}" method="post" enctype="multipart/form-data" class="text-center col-12">
                {% csrf_token %}
                <input type="hidden" name="book_id" value="{{ book.pk }}">
                <label id="text" class="col-12 m-2">Добавить отзыв</label>
                <textarea class="form-control col-11 m-auto" name="text" rows=4></textarea>
                <button type="submit" class="btn btn-success m-2">Отправить</button>
            </form>
        </div>
        {% endif %}
        </div>
        {% for comment in comments %}
            <div class="card mt-3">
                <div class="card-body">
                    <h5 class="card-title">Автор: {{ comment.user.username }}</h5>
                    <p class="card-text">Текст: {{ comment.text }}</p>
                    <p class="card-link">Дата: {{ comment.created_date }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}
{% block scripts %}
{% endblock %}

my_project/webapp/templates/book/book_form.html
<div class="form-group row was-validated">
    <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Название</label>
    <div class="col-sm-6">
        {{ form.name }}
        {% for error in form.name.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
        <small class="form-text text-muted">Обязательное поле</small>
    </div>
</div>
<div class="form-group row was-validated">
    <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Секция</label>
    <div class="col-sm-6">
        {{ form.author }}
        {% for error in form.author.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
        <small class="form-text text-muted">Обязательное поле</small>
    </div>
</div>
<div class="form-group row">
    <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Год издания</label>
    <div class="col-sm-6">
        {{ form.published_year }}
        {% for error in form.published_year.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
    </div>
</div>
<div class="form-group row">
    <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Описание</label>
    <div class="col-sm-6">
        {{ form.description }}
        {% for error in form.description.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
    </div>
</div>
<div class="form-group row">
    <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Файл</label>
    <div class="col-sm-6">
        {{ form.file }}
        {% for error in form.file.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
    </div>
</div>
<div class="form-group row">
    <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Обложка</label>
    <div class="col-sm-6">
        {{ form.picture }}
        {% for error in form.picture.errors %}
            <p class="font-weight-light text-danger d-block small text-center pb-0 mb-0">{{ error }}</p>
        {% endfor %}
    </div>
</div>

my_project/webapp/templates/book/book_list.html
{% extends 'base.html' %}
{% block title %}Список книг{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="font-weight-bold border-bottom pb-2">Список книг</h2>
            {% if user.is_staff %}
                <a role="button" class="btn btn-warning m-0 btn-sm m-2" href="{% url 'webapp:create_book' %}">
                    <span class="text-decoration-none text-dark">Добавить книгу</span>
                </a>
            {% endif %}
        {% for book in book_list %}
            {% include 'book/books.html' %}
        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
{% endblock %}

my_project/webapp/templates/book/book_update.html
{% extends 'base.html' %}
{% block title %}Добавление автора{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добавление автора</h2>
        <form action="{% url 'webapp:update_book' form.instance.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'book/book_form.html' %}
            <button type="submit" class="btn btn-success m-2">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{% url 'webapp:authors' %}">Назад</a>
        </form>
    </div>
{% endblock %}

my_project/webapp/templates/book/books.html
<div id="book-{{ book.pk }}" class="border-bottom pb-2 mb-2 pb-2">
    <a role="button" class="text-decoration-none text-dark font-weight-bold" href="{% url 'webapp:book' book.pk %}">
        <h5 class="text-wrap d-block mb-0 font-weight-bold">
        {{ forloop.counter }}. {{ book.name }}
        ({{ book.published_year }})</h5>
    </a>
    {% if user.is_staff %}
        <a class="text-decoration-none text-dark d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1"
           href="{% url 'webapp:update_book' book.pk %}">
           <span class="small border-bottom border-warning pb-1 font-weight-bold">Редактировать</span></a>
        <a class="text-decoration-none text-dark d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1">
            <span
                id = "delete_btn_{{ book.pk }}"
                data-toggle="modal"
                data-target="#delete_item"
                data-url="{% url 'webapp:delete_book' book.pk %}"
                class="delete_item small border-bottom border-warning pb-1 font-weight-bold"
            >Удалить
            </span>
        </a>
    {% endif %}
    {% if user.is_authenticated %}
        <form id="add-form-{{ book.pk }}" method="get"
            action="{% url 'webapp:add_to_bookcase' book.pk %}" class="d-inline-block">
            {% csrf_token %}
            <div
                class="add_to_bookcase text-decoration-none text-dark d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1"
                data-form_id="add-form-{{ book.pk }}"
            >
           <span class="small border-bottom border-warning pb-1">Добавить к себе</span></div>
        </form>
        <form id="remove-form-{{ book.pk }}" method="get"
            action="{% url 'webapp:remove_from_bookcase' book.pk %}" class="d-inline-block">
            {% csrf_token %}
            <div
                class="remove_from_bookcase text-decoration-none text-dark d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1"
                data-form_id="remove-form-{{ book.pk }}"
                data-book_id="book-{{ book.pk }}"
            >
           <span class="small border-bottom border-warning pb-1">Убрать у себя</span></div>
        </form>
    {% endif %}
</div>
{% include 'delete_modal.html' %}